# Generated by Django 2.0.6 on 2018-06-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_addr', models.CharField(blank=True, default='', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('descr', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('module', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=128)),
                ('atype', models.CharField(choices=[('', ''), ('INT', 'Integer'), ('DBL', 'Double'), ('BOOL', 'Boolean'), ('STR', 'String')], max_length=12)),
                ('default_val', models.CharField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('descr', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('descr', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('header', models.CharField(default='', max_length=64)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='model',
            name='mtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='IndrasNet.ModelType'),
        ),
        migrations.AddField(
            model_name='model',
            name='params',
            field=models.ManyToManyField(blank=True, default='', related_name='parameters', to='IndrasNet.ModelParam'),
        ),
    ]
