# Generated by Django 2.0.6 on 2018-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndrasNet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelparam',
            name='hival',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelparam',
            name='lowval',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
