# Generated by Django 2.0.7 on 2018-07-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndrasNet', '0003_auto_20180613_2109'),
        ('IndrasNet', '0004_model_functional'),
    ]

    operations = [
    ]
