# Generated by Django 2.0.7 on 2018-07-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndrasNet', '0005_merge_20180726_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='disp_name',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
