# Generated by Django 2.0.7 on 2018-07-26 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndrasNet', '0002_modelparam_default_val'),
        ('IndrasNet', '0006_model_disp_name'),
    ]

    operations = [
    ]
