# Generated by Django 2.0.6 on 2018-07-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndrasNet', '0008_auto_20180726_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='plot_type',
            field=models.CharField(choices=[('SC', 'Scatterplot'), ('LN', 'Line')], default=None, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='disp_name',
            field=models.CharField(max_length=130),
        ),
    ]
