# Generated by Django 2.1 on 2018-10-13 03:03

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('IndrasNet', '0010_auto_20180731_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ABMModel',
        ),
    ]
